/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import classes.Historico;
import classes.Usuario;
import dao.HistoricoDAO;
import dao.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leand
 */
public class TelaAtualizacaoSenha extends javax.swing.JFrame {
    private Usuario usuario;
    private ArrayList<Historico> listaHistoricos = new ArrayList<>();
    private ArrayList<Usuario> listaUsuarios = new ArrayList<>();
    /**
     * Creates new form TelaAtualizacaoSenha
     */
    public TelaAtualizacaoSenha() {
        initComponents();
    }
    public TelaAtualizacaoSenha(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setarCampos();
        System.out.println(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenhaAtual = new javax.swing.JLabel();
        passwordFielSenhaAtual = new javax.swing.JPasswordField();
        lblSenhaNova = new javax.swing.JLabel();
        passwordFieldNovaSenha = new javax.swing.JPasswordField();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSenhaAtual.setText("Senha Atual: ");

        passwordFielSenhaAtual.setEditable(false);

        lblSenhaNova.setText("Nova Senha:");

        passwordFieldNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldNovaSenhaActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordFielSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addComponent(lblSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordFieldNovaSenha)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSenhaAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFielSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenhaNova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAtualizar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        //Criando uma sequência de caracteres para poder testar se a senha atende aos requisitos
        char [] senha = passwordFieldNovaSenha.getPassword();
        boolean atualizado;
        UsuarioDAO usuarioDao = new UsuarioDAO();
        
        //Criando um novo histórico para salvar no banco. Dessa forma, toda vez que uma senha é criada, ela vira um histórico, seja ativa
        // ou antiga, para
        //não ser possível outro usuário criar uma senha igual
        Historico hist = new Historico();
        HistoricoDAO histDao = new HistoricoDAO();
        
        //Testes para verificar se a senha atende aos requisitos
        if(validaFormAtualizacao() && validarSenhaAtualizacao(senha) && verificarHistoricoSenhasAtualizacao(String.valueOf(senha)) 
                && compararSenhasAtivasAtualizacao(String.valueOf(senha))){
            
            java.util.Date dataUltimaSenha = new java.util.Date();
            
            usuario.setSenhaUsuario(String.valueOf(senha));
            usuario.setDataUltimaTroca(dataUltimaSenha);
            
            atualizado = usuarioDao.update(usuario);
            
            //Para testar se o usuário foi realmente inserido no banco. Se ele foi inserido, a sua senha deve ser armazenada na lista das
            //últimas 7 senhas
            if (atualizado) {
                JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!");
                
                hist.setIdUsuario(usuario.getIdUsuario());//Esse id do usuário é o id do usuário que está atualizando a senha
                hist.setSenhaAntiga(usuario.getSenhaUsuario());
                
                if(listaHistoricos.size() < 7){
                    histDao.insert(hist);
                }else{
                    Historico historicoSenha = listaHistoricos.get(0);//Pega a primeira senha da lista de senhas do histórico 
                    histDao.excluir(historicoSenha.getIdHistorico()); //Remove a primeira senha da lista(a mais antiga)
                    System.out.println(hist);
                    histDao.insert(hist);//Insere o novo histórico na lista                                    
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar a senha!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        } else if(!validarSenhaAtualizacao(senha)){
            JOptionPane.showMessageDialog(null,
        "A senha deve conter no mínimo 8 caracteres,\ncom pelo menos uma letra maiúscula, uma minúscula,\num número e um caractere especial.");
        }    
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void passwordFieldNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldNovaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizacaoSenha().setVisible(true);
            }
        });
    }
    private void setarCampos(){
        passwordFielSenhaAtual.setText(usuario.getSenhaUsuario());
    }
    
    private boolean validaFormAtualizacao() {
        if (String.valueOf(passwordFieldNovaSenha.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o campo da nova Senha!",
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            passwordFieldNovaSenha.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean verificarHistoricoSenhasAtualizacao(String senha){
        HistoricoDAO senhaDao = new HistoricoDAO();
        listaHistoricos = senhaDao.lista();
        
        for (Historico historico : listaHistoricos) {
            if(historico.getSenhaAntiga().equals(senha)){
                JOptionPane.showMessageDialog(null, "A senha não pode ser igual às anteriores!");
                passwordFieldNovaSenha.requestFocus();
                return false;
            }  
        }
        return true;
    }
    
    private boolean compararSenhasAtivasAtualizacao(String senha){
        UsuarioDAO usuarioDao = new UsuarioDAO();
        listaUsuarios = usuarioDao.lista();
        
        for (Usuario usr : listaUsuarios) {
            if(usr.getSenhaUsuario().equals(senha)){
                JOptionPane.showMessageDialog(this,
                "A senha digitada já está cadastrada para outro usuário!",
                this.getTitle(),
                JOptionPane.ERROR_MESSAGE);
                passwordFieldNovaSenha.requestFocus();
                return false;
            }
            
        }
        return true;
    }
                  
    private boolean validarSenhaAtualizacao(char[] senhaArray) {
        String senha = new String(senhaArray);

        // Expressão regular que cobre todos os requisitos
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#\\$%\\^&\\*\\(\\)_\\+\\-=\\[\\]{};':\"\\\\|,.<>/?]).{8,}$";

        return senha.matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblSenhaNova;
    private javax.swing.JPasswordField passwordFielSenhaAtual;
    private javax.swing.JPasswordField passwordFieldNovaSenha;
    // End of variables declaration//GEN-END:variables
}
