
package view;

import classes.Historico;
import classes.Usuario;
import dao.HistoricoDAO;
import dao.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private  ArrayList<Historico> listaHistoricos = new ArrayList<>();
    private ArrayList<Usuario> listaUsuarios = new ArrayList<>();

    public TelaCadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuarioCadastro = new javax.swing.JTextField();
        lblSenhaCadastro = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        passwordFieldSenhaCadastro = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro de Usuários");

        jLabel1.setText("Usuário:");

        lblSenhaCadastro.setText("Senha:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarioCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(lblSenhaCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldSenhaCadastro, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenhaCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFieldSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //Criando uma sequência de caracteres para poder testar se a senha atende aos requisitos
        char [] senha = passwordFieldSenhaCadastro.getPassword();
        boolean inserido;
        Usuario user = new Usuario();
        UsuarioDAO usuarioDao = new UsuarioDAO();
        
        //Criando um novo histórico para salvar no banco. Dessa forma, toda vez que uma senha é criada, ela vira um histórico, seja ativa
        // ou antiga, para
        //não ser possível outro usuário criar uma senha igual
        Historico hist = new Historico();
        HistoricoDAO histDao = new HistoricoDAO();
        
        //Testes para verificar se a senha atende aos requisitos
        if(validaFormCadastro() && validarSenha(senha) && verificarHistoricoSenhas(String.valueOf(senha)) 
                && compararSenhasAtivas(String.valueOf(senha))){
            
            String nomeUsuario = txtUsuarioCadastro.getText();
            String senhaUsuario = String.valueOf(passwordFieldSenhaCadastro.getPassword());
            
            user.setNomeUsuario(nomeUsuario);
            user.setSenhaUsuario(senhaUsuario);
            
            inserido = usuarioDao.insert(user);
            
            //Para testar se o usuário foi realmente inserido no banco. Se ele foi inserido, a sua senha deve ser armazenada na lista das
            //últimas 7 senhas
            if (inserido) {
                JOptionPane.showMessageDialog(null, "Usuário inserido com sucesso!");
                
                hist.setIdUsuario(user.getIdUsuario());//Esse id do usuário é o que veio do banco no ResultSetGet_tGenerated_Keys)
                hist.setSenhaAntiga(user.getSenhaUsuario());
                
                if(listaHistoricos.size() < 7){
                    histDao.insert(hist);
                }else{
                    Historico historicoSenha = listaHistoricos.get(0);//Pega a primeira senha da lista de senhas do histórico 
                    histDao.excluir(historicoSenha.getIdHistorico()); //Remove a primeira senha da lista(a mais antiga)
                    System.out.println(hist);
                    histDao.insert(hist);//Insere o novo histórico na lista                                    
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário!", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        } else if(!validarSenha(senha)){
            JOptionPane.showMessageDialog(null,
        "A senha deve conter no mínimo 8 caracteres,\ncom pelo menos uma letra maiúscula, uma minúscula,\num número e um caractere especial.");
        }    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        btnCadastrarActionPerformed(null);
    }//GEN-LAST:event_btnCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }
    
    private boolean validaFormCadastro() {
        if (txtUsuarioCadastro.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o campo Usuário!",
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            txtUsuarioCadastro.requestFocus();
            return false;
        }

        if (String.valueOf(passwordFieldSenhaCadastro.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Preencha o campo Senha!",
                    this.getTitle(),
                    JOptionPane.ERROR_MESSAGE);
            passwordFieldSenhaCadastro.requestFocus();
            return false;
        }

        return true;
    }
    
    private boolean verificarHistoricoSenhas(String senha){
        HistoricoDAO senhaDao = new HistoricoDAO();
        listaHistoricos = senhaDao.lista();
        
        for (Historico historico : listaHistoricos) {
            if(historico.getSenhaAntiga().equals(senha)){
                JOptionPane.showMessageDialog(null, "A senha não pode ser igual às anteriores!");
                passwordFieldSenhaCadastro.requestFocus();
                return false;
            }  
        }
        return true;
    }
    
    private boolean compararSenhasAtivas(String senha){
        UsuarioDAO usuarioDao = new UsuarioDAO();
        listaUsuarios = usuarioDao.lista();
        
        for (Usuario usuario : listaUsuarios) {
            if(usuario.getSenhaUsuario().equals(senha)){
                JOptionPane.showMessageDialog(this,
                "A senha digitada já está cadastrada para outro usuário!",
                this.getTitle(),
                JOptionPane.ERROR_MESSAGE);
                passwordFieldSenhaCadastro.requestFocus();
                return false;
            }
            
        }
        return true;
    }
                  
    private boolean validarSenha(char[] senhaArray) {
        String senha = new String(senhaArray);

        // Expressão regular que cobre todos os requisitos
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#\\$%\\^&\\*\\(\\)_\\+\\-=\\[\\]{};':\"\\\\|,.<>/?]).{8,}$";

        return senha.matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSenhaCadastro;
    private javax.swing.JPasswordField passwordFieldSenhaCadastro;
    private javax.swing.JTextField txtUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
